- name: configure hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: set timezones
  community.general.timezone:
    name: "{{ timezone }}"

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
      
      